# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - testing
  pull_request:
    branches: 
      - main
      - testing

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compiles:
    if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'testing'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./client
      run: yarn
    - name: run client 
      working-directory: ./client
      run: yarn start
