# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
      
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'testing'
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./client
      run: yarn
    - name: build client 
      working-directory: ./client
      run: yarn run build
